### ISSUE TITLE
uploading bigger file fails

### ISSUE THREAD

**Issue by yannick** [tamediadigital/vibe-s3#2]
uploading a 30mb lz4 file fails:
`object.Exception occurred at ../../../vibe.d-master/source/vibe/core/drivers/libevent2_tcp.d:431 : Connection error while writing to TCPConnection.`

**Comment by 9il** [comment]
For files greater than 4KB: 

```
vibe.aws.aws.AWSException occurred at ../../source/vibe/aws/aws.d:38 : SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
Task terminated with uncaught exception: SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your key and signing method.
```

**Comment by yannick** [comment]
means that the rolling signature is wrong? iirc this worked before.

**Comment by 9il** [comment]
it may be my bug with delegates

**Comment by 9il** [comment]
Hmm, no, `signature` updates each delegate call :-/

**Comment by 9il** [comment]
Some progress: we should switch to vibe.d chunking instead our current implementation. Will try to do it
