### ISSUE TITLE
Very recent vibe-d dependency

### ISSUE THREAD

**Issue by Marenz** [tamediadigital/vibe-s3#20]
I was just wondering.. do you really depend on features only present in vibe-d ver. `0.8.0-beta.5`? Because of this high version it is not possible to use this dub configuration in projects that use older and more stable versions...

**Comment by yannick** [comment]
@Marenz you can use it with older version, just choose a commit/version before
https://github.com/tamediadigital/vibe-s3/commit/eb295fa5c8a9148c5aac457ce839206212533ecc
