### ISSUE TITLE
Compilation Error using dmd 2.073.0

### ISSUE THREAD

**Issue by AlQurashi** [tamediadigital/vibe-s3#21]
Compiling examples produces:

`source/app.d(105,18): Error: function vibe.aws.s3.S3.upload (string resource, RandomAccessStream input, string contentType = "application/octet-stream", StorageClass storageClass = "STANDARD", ulong chunkSize = 524288LU) is not callable using argument types (string, FileStream, string)`

Although FileStream implements RandomAccessStream

Using the in another program produces the same error.
Any thoughts?

**Comment by yannick** [comment]
maybe related to https://github.com/tamediadigital/vibe-s3/issues/20 ?
not that for older vibe.d versions you need older vibe-s3 version. 
can you provide a gist/repo with code that demonstrates the error?

**Comment by AlQurashi** [comment]
Compiling the `s3` example that is included in the examples folder produces this error, which compiler and vibe version do I need to have it compiled? I tried dmd 2.070.0 all the way to 2.075.0, could not get it compiled

**Comment by yannick** [comment]
@9il can you take a look?

**Comment by 9il** [comment]
yes

**Comment by yannick** [comment]
@AlQurashi is it working now?

**Comment by AlQurashi** [comment]
@yannick yes It does, but I think the interface of the function now is a bit ugly, I am writing some changes to support ACL, If I come up with something regarding the RandomAccessStream I'll be happy to send you a pull request.
